# Generated by Smithery / Subctx for Docker containerization
FROM node:20-alpine

WORKDIR /app

COPY package.json LICENSE README.md smithery.yaml ./
COPY bin ./bin

RUN chmod +x bin/connector.js

ENTRYPOINT ["node", "bin/connector.js"]
